# Example config file for the aggression detection retraining
parameters:

  # (Required) Name of the huggingface or local transformer model
  transformer_model: roberta-base # (String)

  # (Required) Name of the tokenizer
  tokenizer: roberta-base # (String)

  # Maximum sequence length for the text
  max_seq_size: 128 # (String) Default: 512

  # (Required) Number of training epochs
  epochs: 3 # (Integer)

  # Random Seed
  random_seeds: [3, 5, 11, 13, 42]
